services:
#backend
  one-million-store:
    build:
      context: ./one-million-store
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    command: npm run dev
    env_file:
      - .env.backend
    
#frontend
  one-million-store-storefront:
    build:
      context: ./one-million-store-storefront
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: npm run dev
    env_file:
      - .env.frontend

#database
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: medusa-one-million-store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data